// Design tokens ported verbatim from the ui/ mockups' "Midnight Executive" system (see DESIGN.md in each).
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#3c2f00',
        'surface-container-highest': '#38342b',
        'on-tertiary-fixed-variant': '#005137',
        'tertiary-fixed-dim': '#68dba9',
        'surface-tint': '#e9c349',
        'on-tertiary-container': '#004f36',
        'on-tertiary': '#003825',
        'surface-dim': '#16130b',
        surface: '#16130b',
        'on-background': '#eae1d4',
        'error-container': '#93000a',
        'surface-container': '#231f17',
        'on-surface-variant': '#d0c5af',
        'on-secondary-fixed': '#0f0069',
        'secondary-fixed': '#e2dfff',
        'on-error-container': '#ffdad6',
        secondary: '#c3c0ff',
        'on-tertiary-fixed': '#002114',
        'surface-container-high': '#2d2a21',
        'inverse-surface': '#eae1d4',
        'on-error': '#690005',
        'tertiary-container': '#52c796',
        'primary-fixed': '#ffe088',
        'on-primary-fixed-variant': '#574500',
        'on-surface': '#eae1d4',
        tertiary: '#70e3b0',
        'on-secondary-container': '#b3b1ff',
        primary: '#f2ca50',
        'on-primary-fixed': '#241a00',
        'inverse-primary': '#735c00',
        'on-primary-container': '#554300',
        'inverse-on-surface': '#343027',
        'secondary-container': '#3626ce',
        'on-secondary': '#1d00a5',
        'outline-variant': '#4d4635',
        'primary-fixed-dim': '#e9c349',
        outline: '#99907c',
        error: '#ffb4ab',
        'surface-bright': '#3d392f',
        background: '#16130b',
        'secondary-fixed-dim': '#c3c0ff',
        'surface-container-low': '#1f1b13',
        'on-secondary-fixed-variant': '#3323cc',
        'surface-variant': '#38342b',
        'surface-container-lowest': '#110e07',
        'primary-container': '#d4af37',
        'tertiary-fixed': '#85f8c4',
      },
      // "full" intentionally left as Tailwind's native 9999px — DESIGN.md requires avatars/pulse
      // indicators to stay perfectly circular, which the mockups' own override (0.75rem) breaks.
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
      spacing: {
        unit: '4px',
        'margin-safe': '32px',
        gutter: '24px',
        'panel-padding': '40px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
